import {ClerkProvider, SignInButton, SignUpButton, Show, UserButton} from "@clerk/nextjs";
import { shadcn } from "@clerk/ui/themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { AnalysisNotifications } from "@/components/analysis-notifications";
import { TimezoneSetting } from "@/components/TimezoneSetting";
import { getUserTimezone, hasUserTimezone } from "@/lib/user-timezone";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const timezoneSet = await hasUserTimezone();
  const timezone = timezoneSet ? await getUserTimezone() : null;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider appearance={{ theme: shadcn }}>
          <header className="flex justify-between items-center gap-3 px-4 py-3 border-b">
            <nav className="flex items-center gap-4 text-sm font-medium">
              <Link href="/">Search</Link>
              <Link href="/watchlist">Watchlist</Link>
              <Link href="/queue">Queue</Link>
              <Link href="/alerts">Alerts</Link>
            </nav>
            <div className="flex items-center gap-3">
              <Show when="signed-in">
                <TimezoneSetting currentTimezone={timezone} />
              </Show>
              <Show when="signed-out">
                <SignInButton />
                <SignUpButton />
              </Show>
              <Show when="signed-in">
                <UserButton />
              </Show>
            </div>
          </header>
          {children}
          <Show when="signed-in">
            <AnalysisNotifications />
          </Show>
        </ClerkProvider>
      </body>
    </html>
  );
}